spring.application.name=biblioteca-backend
spring.config.import=optional:file:.env[.properties]
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB
app.storage.provider=${APP_STORAGE_PROVIDER:local}
app.storage.r2.endpoint=${R2_ENDPOINT:}
app.storage.r2.access-key-id=${R2_ACCESS_KEY_ID:}
app.storage.r2.secret-access-key=${R2_SECRET_ACCESS_KEY:}
app.storage.r2.bucket=${R2_BUCKET_NAME:}
app.storage.r2.region=${R2_REGION:auto}
