spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
app.storage.temporary-directory=temp/book
app.storage.cover-directory=temp/cover
app.storage.permanent-directory=storage
app.storage.provider=local
