spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
app.storage.temporary-directory=${TEMPORARY_DIRECTORY:temp/book}
app.storage.cover-directory=${COVER_DIRECTORY:temp/cover}
app.storage.permanent-directory=${PERMANENT_DIRECTORY:storage}
app.storage.provider=${APP_STORAGE_PROVIDER:local}
app.storage.r2.endpoint=${R2_ENDPOINT:}
app.storage.r2.access-key-id=${R2_ACCESS_KEY_ID:}
app.storage.r2.secret-access-key=${R2_SECRET_ACCESS_KEY:}
app.storage.r2.bucket=${R2_BUCKET_NAME:}
app.storage.r2.region=${R2_REGION:auto}
